# Model arguments
model_name_or_path: codellama/Codellama-7b-Instruct-hf
torch_dtype: auto
use_flash_attention_2: true


# LoRA arguments
use_peft: true
load_in_8bit: true
lora_r: 128
lora_alpha: 256
lora_dropout: 0.1
lora_target_modules:
- q_proj
- k_proj
- v_proj
- o_proj

# Data training arguments
dataset_mixer:
  /workspace/s3/hf/datasets/python_code_cleaned : 1
dataset_splits:
- train
- validation
preprocessing_num_workers: 12

# SFT trainer config
bf16: false
do_eval: true
gradient_accumulation_steps: 4
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
hub_model_id: codellama-7b-sft-lora-func-names
hub_strategy: end
learning_rate: 4.0e-05
log_level: info
logging_steps: 5  
logging_strategy: steps
lr_scheduler_type: cosine
max_seq_length: 2048
max_steps: 960
num_train_epochs: 1
output_dir: /workspace/s3/hf/experiments/codellama-7b-sft-lora-func-names
overwrite_output_dir: true
per_device_eval_batch_size: 1
per_device_train_batch_size: 4
push_to_hub: true
report_to:
- wandb
save_total_limit: 3
save_strategy: "steps"
save_steps: 0.2
seed: 42
warmup_ratio: 0.1

# Eval
evaluation_strategy: steps
eval_steps: 0.2